### ISSUE TITLE
4.2 Correcciones BPMN

### ISSUE THREAD

**Issue by ManuelLR** [DPIRPSG/IR#9]

**Comment by ManuelLR** [comment]
- Poner la frase del final del parrafo la primera.
- Si los BPMN han cambiado un poco describirlo con palabras (sin poner de nuevo el gráfico).
- Los actores no se repiten.

**Comment by migrodcab** [comment]
Listo @f00e0bd74ecac806306feb5dcc681da78b69d5bf
